#include<stdio.h>
int a;
int main(){
    scanf("%d",&a);
    while((a/1000)>=1){
        printf("M");
        a=a-1000;
    }
    if(a/900==1){
        printf("CM");
        a=a-900;
    }
    while((a/500)>=1){
        printf("D");
        a=a-500;
    }
    if(a/400==1){
        printf("CD");
        a=a-400;
    }
    while(a/100>=1){
        printf("C");
        a=a-100;
    }
    if(a/90==1){
        printf("XC");
        a=a-90;
    }
    while(a/50>=1){
        printf("L");
        a=a-50;
    }
    if(a/40==1){
        printf("XL");
        a=a-40;
    }
    while(a/10>=1){
        printf("X");
        a=a-10;
    }
    if(a/9==1){
        printf("IX");
        a=a-9;
    }
    while(a/5>=1){
        printf("V");
        a=a-5;
    }
    if(a/4==1){
        printf("IV");
        a=a-4;
    }
    while(a>=1){
        printf("I");
        a=a-1;
    }
    return 0;
}

